Update compiler version to 1.20.7
multiversx/mx-chain-scripts pull request #12
Opened 2023-08-11 09:51 UTC by valentin-lup

Update compiler version to 1.20.7

2023-08-11 09:52 UTC, AdoAdoAdo approved these changes

2023-08-11 09:57 UTC, iulianpascalau requested changes
we need to test firsthand

2023-08-22 08:03 UTC, iulianpascalau approved these changes

2023-08-22 08:04 UTC, iulianpascalau commented
> we need to test firsthand

done

2023-08-22 08:11 UTC, merged